name: Test

on:
  - pull_request
  - push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run FOSSA scan and upload build data
        uses: ./
        with:
          fossa-api-key: 570e8f8e839e20a229f196974ede9a4d
